#!/usr/bin/perl
use warnings;
use strict;

my $seq = 'AACAGCACGGCAACGCTGTGCCTTGGGCACCATGCAGTACCAAACGGAACGATAGTGAAAACAATCACGA ATGACCAAATTGAAGTTACTAATGCTACTGAGCTGGTTCAGAGTTCCTCAACAGGTGAAATATGCGACAG TCCTCATCAGATCCTTGATGGAGAAAACTGCACACTAATAGATGCTCTATTGGGAGACCCTCAGTGTGAT GGCTTCCAAAATAAGAAATGGGACCTTTTTGTTGAACGCAGCAAAGCCTACAGCAACTGTTACCCTTATG ATGTGCCGGATTATGCCTCCCTTAGGTCACTAGTTGCCTCATCCGGCACACTGGAATTTAACAATGAAAG CTTCAATTGGACTGGAGTCACTCAAAATGGAATCAGCTCTGCTTGCAAAAGGAGATCTAATAACAGTTTC TTTAGTAGATTGAATTGGTTGACCCACTTAAAATTCAAATACCCAGCATTGAACGTGACTATGCCAAACA ATGAAAAATTTGACAAATTGTACATTTGGGGGGTTCACCACCCGGGTACGGACAATGACCAAATCTTCCT GTATGCTCAAGCATCAGGAAGAATCACAGTCTCTACCAAAAGAAGCCAACAGACTGTAATCCCGAATATC GGATCTAGACCCAGAGTAAGGAATATCCCCAGCAGAATAAGCATCTATTGGACAATAGTAAAACCGGGAG ACATACTTTTGATTAACAGCACAGGGAATTTAATTGCTCCTAGGGGTTACTTCAAAATACGAAGTGGGAA AAGCTCAATAATGAGATCAGATGCACCCATTGGCAAATGCAATTCTGAATGCATCACTCCAAATGGAAGC ATTCCCAATGACAAACCATTTCAAAATGTAAACAGGATCACATATGGGGCCTGGCCCAGATATGTTAAGC AAAACACTCTGAAATTGGCAACAGGGATGCGAAATGTACCAGAGAAACAAACTAGAGGCATATTTGGCGC AATCGCGGGTTTCATAGAAAATGGTTGGGAAGGAATGGTGGATGGTTGGTACGGTTT';

$seq =~ s/\s//g;

my $restrictionSite1 = "(GA[ACT]TC)";
my $restrictionSite2 = "(GCC[AT]GG)";

my @restriction1_sites = find_site($restrictionSite1, $seq);
my @restriction2_sites = find_site($restrictionSite2, $seq);

print "Restriction Sites #1\n";
print_results(@restriction1_sites);

print "Restriction Sites #2\n";
print_results(@restriction2_sites);

# Search regex motif against DNA
# find_site (pattern, sequence)
#
# Returns array of printed statements defining
# positions and regex match

sub find_site {
	my @results;
	(my $pattern, my $sequence) = @_;

	while ($sequence =~ /$pattern/ig){
		my $position = $-[0] + 1;
		push @results, "$&\nThe match was at position: $position\n\n";
	}

	return sort@results;
}

sub print_results {
	foreach(@_){
		print $_, "\n";
	}
}
